### ISSUE TITLE
这两个样式与设计图不一致

### ISSUE THREAD

**Issue by YamCao** [loslife/BeautyTool-Issue#613]
![5348dab3-6f54-42a5-abd5-e865db7c9b20](https://cloud.githubusercontent.com/assets/7477975/9055756/3e1c81c4-3ac0-11e5-9044-204ccb947cad.png)
![36f81b51-fb17-4ead-b131-74be3a8f1429](https://cloud.githubusercontent.com/assets/7477975/9055757/3e47116e-3ac0-11e5-8a93-ad72bd09a718.png)

**Comment by zhenghonglei** [comment]
移到美蜜问题库
